# Use a base Python image
FROM python:3.9-slim

# Install necessary libraries (matplotlib and plotly)
RUN pip install --no-cache-dir matplotlib plotly

# Set the working directory inside the container
WORKDIR /app

# Set the default command to run when the container starts
CMD ["python"]
